import { colors } from '@/components/system/colors';
import { Footer } from '@/components/presenters/organisms/Footer';
import { Header } from '@/components/presenters/organisms/Header';
import '@/styles/globals.css';
import '@/styles/reset.css';
import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';

const NotoSansJP = Noto_Sans_JP({
	weight: ['500', '600', '700'],
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-NotoSansJP',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="ja"
			className={`${NotoSansJP.variable}`}
			style={{
				minHeight: '100vh',
				backgroundColor: colors.background.base,
			}}
		>
			<body className={`flex flex-col`} style={{ minHeight: '100vh' }}>
				<Header />
				<main className="container grow mx-auto">{children}</main>
				<Footer />
			</body>
		</html>
	);
}
